name: Deploy to wgptix.com

on:
  push:
    branches: [main]

concurrency:
  group: deploy-wgptix
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust server host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to DirectAdmin
        shell: bash
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" 'bash -se' <<'EOSSH'
          set -e

          DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
          REPO_SSH="git@github.com:mikhaelfelian/p56-wgtix.git"
          BRANCH="main"

          mkdir -p "$DEPLOY_PATH"
          cd "$DEPLOY_PATH" || { echo "Path not found: $DEPLOY_PATH"; exit 1; }

          if [ -d .git ]; then
            git remote set-url origin "$REPO_SSH" || true
            git fetch --all --prune
            git checkout "$BRANCH" || true
            git reset --hard "origin/$BRANCH"
            git clean -fd
          else
            # kosongkan isi lama bila ada file acak (opsional, hapus jika tak ingin)
            if [ -n "$(ls -A "$DEPLOY_PATH" 2>/dev/null)" ]; then
              TS=$(date +%Y%m%d-%H%M%S)
              tar -czf "/home/janusv/backup-wgptix-public_html-$TS.tgz" . || true
              rm -rf ./* .[^.] .??* 2>/dev/null || true
            fi
            git clone -b "$BRANCH" "$REPO_SSH" .
          fi

          if command -v composer >/dev/null 2>&1; then
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction || true
          fi

          if command -v php >/dev/null 2>&1; then
            php spark migrate --all --ansi || true
            php -r 'if(function_exists("opcache_reset")){ opcache_reset(); }'
          fi
          EOSSH
